apiVersion: v2
name: helm-chart-test
description: |-
  A Helm chart example.
  Documentation
  For additional details regarding install parameters check Helm Chart documentation at https://github.com/durgeshsingh2065/helm-repo
  License
  By installing this product you accept the following license terms: https://github.com/durgeshsingh2065/helm-repo
  
icon: https://durgeshsingh2065github.io/helm-chart/test.png
home: https://github.com/durgeshsingh2065/helm-repo
keywords:
  - amd64 
  - RHOCP
  - Other
# A chart can be either an 'application' or a 'library' chart.
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 6.0.0.2.03

# Kubernetes Version
kubeVersion: '>=1.19.0'

maintainers:
- name: Durgesh
